### Practice

### Basic Feedforward Neural Network

In [1]:
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms


# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Hyper-parameters 
input_size = 784
hidden_size = 500
num_classes = 10
num_epochs = 5
batch_size = 100
learning_rate = 0.001

# MNIST dataset 
train_dataset = torchvision.datasets.MNIST(root='../../data', 
                                           train=True, 
                                           transform=transforms.ToTensor(),  
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='../../data', 
                                          train=False, 
                                          transform=transforms.ToTensor())

# Data loader
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, 
                                           batch_size=batch_size, 
                                           shuffle=True)

test_loader = torch.utils.data.DataLoader(dataset=test_dataset, 
                                          batch_size=batch_size, 
                                          shuffle=False)

# Fully connected neural network with one hidden layer
class NeuralNet(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size) 
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, num_classes)  
    
    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        return out

model = NeuralNet(input_size, hidden_size, num_classes).to(device)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)  

# Train the model
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (images, labels) in enumerate(train_loader):  
        # Move tensors to the configured device
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        if (i+1) % 100 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}' 
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))

# Test the model
# In test phase, we don't need to compute gradients (for memory efficiency)
with torch.no_grad():
    correct = 0
    total = 0
    for images, labels in test_loader:
        images = images.reshape(-1, 28*28).to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

    print('Accuracy of the network on the 10000 test images: {} %'.format(100 * correct / total))

# Save the model checkpoint
torch.save(model.state_dict(), 'model.ckpt')

Processing...
Done!
Epoch [1/5], Step [100/600], Loss: 0.3677
Epoch [1/5], Step [200/600], Loss: 0.4022
Epoch [1/5], Step [300/600], Loss: 0.1519
Epoch [1/5], Step [400/600], Loss: 0.1776
Epoch [1/5], Step [500/600], Loss: 0.2595
Epoch [1/5], Step [600/600], Loss: 0.1373
Epoch [2/5], Step [100/600], Loss: 0.1786
Epoch [2/5], Step [200/600], Loss: 0.1175
Epoch [2/5], Step [300/600], Loss: 0.0637
Epoch [2/5], Step [400/600], Loss: 0.1429
Epoch [2/5], Step [500/600], Loss: 0.0477
Epoch [2/5], Step [600/600], Loss: 0.0308
Epoch [3/5], Step [100/600], Loss: 0.1091
Epoch [3/5], Step [200/600], Loss: 0.0792
Epoch [3/5], Step [300/600], Loss: 0.0726
Epoch [3/5], Step [400/600], Loss: 0.0663
Epoch [3/5], Step [500/600], Loss: 0.2364
Epoch [3/5], Step [600/600], Loss: 0.1143
Epoch [4/5], Step [100/600], Loss: 0.0047
Epoch [4/5], Step [200/600], Loss: 0.0534
Epoch [4/5], Step [300/600], Loss: 0.0441
Epoch [4/5], Step [400/600], Loss: 0.0938
Epoch [4/5], Step [500/600], Loss: 0.0460
Epoch [4/5], S

### Basic Digital Image Processing SK Image

In [4]:
from skimage import data, io, filters
image = data.astronaut()
noisyimage = filters.gaussian(image)
io.imshow(image)
io.imshow(noisyimage)

C:\Users\Malcolm\AppData\Local\conda\conda\envs\pytorch\lib\site-packages\skimage\filters\_gaussian.py:108: RuntimeWarning: Images with dimensions (M, N, 3) are interpreted as 2D+RGB by default. Use `multichannel=False` to interpret as 3D image with last dimension of length 3.
  warn(RuntimeWarning(msg))


## Torch Tutorial

In [23]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
print(x)

y = torch.rand(5, 3)
print(y)

z = torch.zeros(5, 3, dtype=torch.long)
print(z)

a = torch.tensor([5.5, 3])
print(a)

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

print(x.size())

y = torch.rand(5, 3)
print(x + y)

print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# adds x to y
y.add_(x)
print(y)

print(x)
print(x[:, 1])

tensor([[-1.6837e-35,  4.3300e-43, -1.6837e-35],
        [ 4.3300e-43,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -1.6837e-35],
        [ 4.3300e-43, -1.6837e-35,  4.3300e-43],
        [-1.6837e-35,  4.3300e-43, -1.6837e-35]])
tensor([[0.2098, 0.1308, 0.3857],
        [0.9595, 0.6455, 0.1358],
        [0.0117, 0.8315, 0.7430],
        [0.7360, 0.8733, 0.3937],
        [0.8377, 0.0287, 0.6710]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4509,  2.0286, -2.1093],
        [ 0.4697, -0.9924, -0.8261],
        [ 1.9916,  1.3931,  0.4162],
        [ 0.1486, -0.0721,  1.4633],
        [-1.0232,  0.3651,  1.3171]])
torch.Size([5, 3])
tensor([[ 1.0100,  2.9546, -1.3902],
        [ 1.0165, -0.8333,  0.0576],
        [ 2.3434,  1.4956,  1.0507],
        [ 0.66

In [31]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

x = torch.randn(1)
print(x)
print(x.item())

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a.add_(1)
print(a)
print(b)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([1.5125])
1.512548565864563
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [32]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [33]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([2.5125], device='cuda:0')
tensor([2.5125], dtype=torch.float64)
